ansible.builtin.ping:
  params:
  - data
  aliases: {}
  freeform: false
  supported: data.
  reports_as:
    short: ping
    fqcn: ansible.builtin.ping
ansible.builtin.command:
  params:
  - argv
  - chdir
  - cmd
  - creates
  - expand_argument_vars
  - removes
  - stdin
  - stdin_add_newline
  - strip_empty_ends
  aliases: {}
  freeform: true
  supported: _raw_params, _uses_shell, argv, chdir, cmd, creates, executable, expand_argument_vars, removes, stdin, stdin_add_newline, strip_empty_ends.
  reports_as:
    short: ansible.legacy.command
    fqcn: ansible.legacy.command
ansible.builtin.shell:
  params:
  - chdir
  - cmd
  - creates
  - executable
  - removes
  - stdin
  - stdin_add_newline
  aliases: {}
  freeform: true
  supported: _raw_params, _uses_shell, argv, chdir, cmd, creates, executable, expand_argument_vars, removes, stdin, stdin_add_newline, strip_empty_ends.
  reports_as:
    short: ansible.legacy.command
    fqcn: ansible.legacy.command
ansible.builtin.copy:
  params:
  - attributes
  - backup
  - checksum
  - content
  - decrypt
  - dest
  - directory_mode
  - follow
  - force
  - group
  - local_follow
  - mode
  - owner
  - remote_src
  - selevel
  - serole
  - setype
  - seuser
  - src
  - unsafe_writes
  - validate
  aliases:
    attr: attributes
  freeform: false
  supported: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr).
  reports_as:
    short: ansible.legacy.copy
    fqcn: ansible.legacy.copy
ansible.builtin.file:
  params:
  - access_time
  - access_time_format
  - attributes
  - follow
  - force
  - group
  - mode
  - modification_time
  - modification_time_format
  - owner
  - path
  - recurse
  - selevel
  - serole
  - setype
  - seuser
  - src
  - state
  - unsafe_writes
  aliases:
    attr: attributes
    dest: path
    name: path
  freeform: false
  supported: _diff_peek, _original_basename, access_time, access_time_format, attributes, follow, force, group, mode, modification_time, modification_time_format, owner, path, recurse, selevel, serole, setype, seuser, src, state, unsafe_writes (attr, dest, name).
  reports_as:
    short: file
    fqcn: ansible.builtin.file
ansible.builtin.user:
  params:
  - append
  - authorization
  - comment
  - create_home
  - expires
  - force
  - generate_ssh_key
  - group
  - groups
  - hidden
  - home
  - local
  - login_class
  - move_home
  - name
  - non_unique
  - password
  - password_expire_account_disable
  - password_expire_max
  - password_expire_min
  - password_expire_warn
  - password_lock
  - profile
  - remove
  - role
  - seuser
  - shell
  - skeleton
  - ssh_key_bits
  - ssh_key_comment
  - ssh_key_file
  - ssh_key_passphrase
  - ssh_key_type
  - state
  - system
  - uid
  - uid_max
  - uid_min
  - umask
  - update_password
  aliases:
    createhome: create_home
    user: name
  freeform: false
  supported: append, authorization, comment, create_home, expires, force, generate_ssh_key, group, groups, hidden, home, local, login_class, move_home, name, non_unique, password, password_expire_account_disable, password_expire_max, password_expire_min, password_expire_warn, password_lock, profile, remove, role, seuser, shell, skeleton, ssh_key_bits, ssh_key_comment, ssh_key_file, ssh_key_passphrase, ssh_key_type, state, system, uid, uid_max, uid_min, umask, update_password (createhome, user).
  reports_as:
    short: user
    fqcn: ansible.builtin.user
ansible.builtin.group:
  params:
  - force
  - gid
  - gid_max
  - gid_min
  - local
  - name
  - non_unique
  - state
  - system
  aliases: {}
  freeform: false
  supported: force, gid, gid_max, gid_min, local, name, non_unique, state, system.
  reports_as:
    short: group
    fqcn: ansible.builtin.group
ansible.builtin.dnf:
  params:
  - allow_downgrade
  - allowerasing
  - autoremove
  - best
  - bugfix
  - cacheonly
  - conf_file
  - disable_excludes
  - disable_gpg_check
  - disable_plugin
  - disablerepo
  - download_dir
  - download_only
  - enable_plugin
  - enablerepo
  - exclude
  - install_weak_deps
  - installroot
  - list
  - lock_timeout
  - name
  - nobest
  - releasever
  - security
  - skip_broken
  - sslverify
  - state
  - update_cache
  - update_only
  - use_backend
  - validate_certs
  aliases:
    pkg: name
    expire-cache: update_cache
  freeform: false
  supported: allow_downgrade, allowerasing, autoremove, best, bugfix, cacheonly, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_weak_deps, installroot, list, lock_timeout, name, nobest, releasever, security, skip_broken, sslverify, state, update_cache, update_only, use_backend, validate_certs (expire-cache, pkg).
  reports_as:
    short: ansible.legacy.dnf
    fqcn: ansible.legacy.dnf
ansible.builtin.apt:
  params:
  - allow_change_held_packages
  - allow_downgrade
  - allow_unauthenticated
  - auto_install_module_deps
  - autoclean
  - autoremove
  - cache_valid_time
  - clean
  - deb
  - default_release
  - dpkg_options
  - fail_on_autoremove
  - force
  - force_apt_get
  - install_recommends
  - lock_timeout
  - name
  - only_upgrade
  - policy_rc_d
  - purge
  - state
  - update_cache
  - update_cache_retries
  - update_cache_retry_max_delay
  - upgrade
  aliases:
    allow-downgrade: allow_downgrade
    allow-downgrades: allow_downgrade
    allow_downgrades: allow_downgrade
    allow-unauthenticated: allow_unauthenticated
    default-release: default_release
    install-recommends: install_recommends
    package: name
    pkg: name
    update-cache: update_cache
  freeform: false
  supported: allow_change_held_packages, allow_downgrade, allow_unauthenticated, auto_install_module_deps, autoclean, autoremove, cache_valid_time, clean, deb, default_release, dpkg_options, fail_on_autoremove, force, force_apt_get, install_recommends, lock_timeout, only_upgrade, package, policy_rc_d, purge, state, update_cache, update_cache_retries, update_cache_retry_max_delay, upgrade (allow-downgrade, allow-downgrades, allow-unauthenticated, allow_downgrades, default-release, install-recommends, name, pkg, update-cache).
  reports_as:
    short: apt
    fqcn: ansible.builtin.apt
ansible.builtin.package:
  params:
  - name
  - state
  - use
  aliases:
    pkg: name
    expire-cache: update_cache
  freeform: false
  supported: allow_downgrade, allowerasing, autoremove, best, bugfix, cacheonly, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_weak_deps, installroot, list, lock_timeout, name, nobest, releasever, security, skip_broken, sslverify, state, update_cache, update_only, use_backend, validate_certs (expire-cache, pkg).
  reports_as:
    short: ansible.legacy.dnf
    fqcn: ansible.legacy.dnf
ansible.builtin.service:
  params:
  - arguments
  - enabled
  - name
  - pattern
  - runlevel
  - sleep
  - state
  - use
  aliases:
    args: arguments
    daemon-reexec: daemon_reexec
    daemon-reload: daemon_reload
    service: name
    unit: name
  freeform: false
  supported: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state (daemon-reexec, daemon-reload, service, unit).
  reports_as:
    short: ansible.legacy.systemd
    fqcn: ansible.legacy.systemd
ansible.builtin.systemd_service:
  params:
  - daemon_reexec
  - daemon_reload
  - enabled
  - force
  - masked
  - name
  - no_block
  - scope
  - state
  aliases:
    daemon-reexec: daemon_reexec
    daemon-reload: daemon_reload
    service: name
    unit: name
  freeform: false
  supported: daemon_reexec, daemon_reload, enabled, force, masked, name, no_block, scope, state (daemon-reexec, daemon-reload, service, unit).
  reports_as:
    short: systemd_service
    fqcn: ansible.builtin.systemd_service
ansible.builtin.lineinfile:
  params:
  - attributes
  - backrefs
  - backup
  - create
  - encoding
  - firstmatch
  - group
  - insertafter
  - insertbefore
  - line
  - mode
  - owner
  - path
  - regexp
  - search_string
  - selevel
  - serole
  - setype
  - seuser
  - state
  - unsafe_writes
  - validate
  aliases:
    attr: attributes
    value: line
    dest: path
    destfile: path
    name: path
    regex: regexp
  freeform: false
  supported: attributes, backrefs, backup, create, encoding, firstmatch, group, insertafter, insertbefore, line, mode, owner, path, regexp, search_string, selevel, serole, setype, seuser, state, unsafe_writes, validate (attr, dest, destfile, name, regex, value).
  reports_as:
    short: lineinfile
    fqcn: ansible.builtin.lineinfile
ansible.builtin.template:
  params:
  - attributes
  - backup
  - block_end_string
  - block_start_string
  - comment_end_string
  - comment_start_string
  - dest
  - follow
  - force
  - group
  - lstrip_blocks
  - mode
  - newline_sequence
  - output_encoding
  - owner
  - selevel
  - serole
  - setype
  - seuser
  - src
  - trim_blocks
  - unsafe_writes
  - validate
  - variable_end_string
  - variable_start_string
  aliases:
    attr: attributes
  freeform: false
  supported: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr).
  reports_as:
    short: ansible.legacy.copy
    fqcn: ansible.legacy.copy
ansible.builtin.debug:
  params:
  - msg
  - var
  - verbosity
  aliases: {}
  freeform: false
  supported: msg, var, verbosity.
  reports_as:
    short: debug
    fqcn: ansible_collections.ansible.builtin.plugins.action.debug
ansible.builtin.setup:
  params:
  - fact_path
  - filter
  - gather_subset
  - gather_timeout
  aliases: {}
  freeform: false
  supported: fact_path, filter, gather_subset, gather_timeout.
  reports_as:
    short: setup
    fqcn: ansible.builtin.setup
known:
- add_host
- apt
- apt_key
- apt_repository
- assemble
- assert
- async_status
- blockinfile
- command
- copy
- cron
- deb822_repository
- debconf
- debug
- dnf
- dnf5
- dpkg_selections
- expect
- fail
- fetch
- file
- find
- gather_facts
- get_url
- getent
- git
- group
- group_by
- hostname
- import_playbook
- import_role
- import_tasks
- include_role
- include_tasks
- include_vars
- iptables
- known_hosts
- lineinfile
- meta
- mount_facts
- package
- package_facts
- pause
- ping
- pip
- raw
- reboot
- replace
- rpm_key
- script
- service
- service_facts
- set_fact
- set_stats
- setup
- shell
- slurp
- stat
- subversion
- systemd
- systemd_service
- sysvinit
- tempfile
- template
- unarchive
- uri
- user
- validate_argument_spec
- wait_for
- wait_for_connection
- yum_repository
twins:
  ansible.builtin.systemd: ansible.builtin.systemd_service
redirects:
  ansible.builtin.yum: ansible.builtin.dnf
tombstones:
  ansible.builtin.include:
    kind: action
    message: The 'ansible.builtin.include' action plugin has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16.
  ansible.builtin.bigip_asm_policy:
    kind: module
    message: The 'ansible.builtin.bigip_asm_policy' module has been removed. bigip_asm_policy has been removed please use bigip_asm_policy_manage instead. This feature was removed from ansible-core in a release after 2019-11-06.
  ansible.builtin.bigip_facts:
    kind: module
    message: The 'ansible.builtin.bigip_facts' module has been removed. bigip_facts has been removed please use bigip_device_info module. This feature was removed from ansible-core in a release after 2019-11-06.
  ansible.builtin.bigip_gtm_facts:
    kind: module
    message: The 'ansible.builtin.bigip_gtm_facts' module has been removed. bigip_gtm_facts has been removed please use bigip_device_info module. This feature was removed from ansible-core in a release after 2019-11-06.
